#!/usr/bin/env python3

import json
import subprocess  # nosec


def _main() -> None:
    with open("github_app_geo_project/project-schema.json", encoding="utf-8") as config_schema_file:
        project_schema = json.load(config_schema_file)
    with open("github_app_geo_project/application-schema.json", encoding="utf-8") as process_schema_file:
        application_schema = json.load(process_schema_file)

        application_schema["$defs"]["project-configuration"] = project_schema["$defs"][
            "project-configuration"
        ]
    with open("github_app_geo_project/application-schema.json", "w", encoding="utf-8") as process_schema_file:
        json.dump(application_schema, process_schema_file, indent=2)

    subprocess.run(  # nosec
        [
            "pre-commit",
            "run",
            "--color=never",
            "--files=github_app_geo_project/application-schema.json",
            "prettier",
        ]
    )


if __name__ == "__main__":
    _main()
