inherits:
  - duplicated
  - utils:base
  - utils:no-design-checks
  - utils:c2cwsgiutils

ignore-paths:
  - github_app_geo_project/project_configuration.py
  - github_app_geo_project/application_configuration.py
  - github_app_geo_project/module/standard/changelog_configuration.py
  - github_app_geo_project/module/audit/configuration.py
  - github_app_geo_project/module/clean/configuration.py

mypy:
  options:
    python-version: '3.11'

ruff:
  options:
    target-version: py311
