inherits:
  - duplicated
  - utils:base
  - utils:fix
  - utils:no-design-checks

doc-warnings: true

ignore-paths:
  - github_app_geo_project/project_configuration.py
  - github_app_geo_project/application_configuration.py

bandit:
  options:
    config: .bandit.yaml
