inherits:
  - duplicated
  - utils:base
  - utils:no-design-checks
  - utils:c2cwsgiutils
  - utils:fix

ignore-paths:
  - github_app_geo_project/project_configuration.py
  - github_app_geo_project/application_configuration.py
  - github_app_geo_project/module/changelog/configuration.py
  - github_app_geo_project/module/audit/configuration.py
  - github_app_geo_project/module/clean/configuration.py
  - github_app_geo_project/module/versions/configuration.py
  - github_app_geo_project/module/backport/configuration.py
  - github_app_geo_project/module/delete_old_workflow_runs/configuration.py
  - github_app_geo_project/module/pull_request/checks_configuration.py
  - github_app_geo_project/module/pull_request/links_configuration.py
  - github_app_geo_project/module/auto_review_merge_close/configuration.py

mypy:
  options:
    python-version: '3.11'

ruff:
  options:
    target-version: py311
