version: '2.2'

services:
  application: &app
    command:
      - pserve
      - --reload
      - c2c:///app/development.ini
    volumes:
      - ./github_app_geo_project:/app/github_app_geo_project:ro

  slave:
    volumes:
      - ./github_app_geo_project:/app/github_app_geo_project:ro

  # test:
  #   volumes:
  #     - ./github_app_geo_project:/app/github_app_geo_project:ro
