services:
  application:
    command:
      - uvicorn
      - github_app_geo_project.app:app
      - --host=0.0.0.0
      - --port=8080
      - --reload
      - --reload-dir=/app/
      - --reload-include=c2casgiutils/**/*.py
      - --reload-include=c2casgiutils/**/*.html
    volumes:
      - ./github_app_geo_project:/app/github_app_geo_project/:ro

  worker:
    volumes:
      - ./github_app_geo_project:/app/github_app_geo_project:ro

  # test:
  #   volumes:
  #     - ./github_app_geo_project:/app/github_app_geo_project:ro
