services:
  application:
    command:
      - pserve
      - --reload
      - c2c:///app/production.ini
    volumes:
      - ./github_app_geo_project:/app/github_app_geo_project/:ro

  worker:
    volumes:
      - ./github_app_geo_project:/app/github_app_geo_project:ro

  # test:
  #   volumes:
  #     - ./github_app_geo_project:/app/github_app_geo_project:ro
