version: '2.2'

services:
  db:
    image: camptocamp/postgres:14-postgis-3
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: tests
    volumes:
      - ./docker/test-db:/docker-entrypoint-initdb.d:ro

  application: &app
    image: camptocamp/github-app-geo-project
    environment: &app-env
      LOG_LEVEL: INFO
      C2C_AUTH_GITHUB_REPOSITORY: camptocamp/github-app-geo-project
      C2C_AUTH_GITHUB_SECRET: '1234567890123456789'
      C2C_AUTH_GITHUB_CLIENT_ID: '1234'
      C2C_AUTH_GITHUB_CLIENT_SECRET: '1234'
      C2C_PROMETHEUS_PORT: '9110'
    links:
      - db

  slave:
    <<: *app
    command:
      - process-queue
    environment:
      <<: *app-env

  test:
    image: camptocamp/github-app-geo-project-tests
    working_dir: /app
    environment:
      LOG_LEVEL: DEBUG
    command:
      - sleep
      - infinity
    links:
      - db
