services:
  db:
    image: camptocamp/postgres:18-postgis-3
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: tests
    volumes:
      - ./docker/test-db:/docker-entrypoint-initdb.d:ro

  application: &app
    image: camptocamp/github-app-geo-project
    build:
      context: .
      target: runner
    environment: &app-env
      C2C__AUTH__GITHUB__REPOSITORY: camptocamp/github-app-geo-project
      C2C__AUTH__GITHUB__SECRET: '1234567890123456789'
      C2C__AUTH__GITHUB__CLIENT_ID: '1234'
      C2C__AUTH__GITHUB__CLIENT_SECRET: '1234'
      C2C__AUTH__TEST__USERNAME: test
      C2C__HTTP: 'true'
      C2C__PROMETHEUS__PORT: 9110
      GHCI__TEST__APP_NAME: test
      GHCI__SQLALCHEMY__URL: postgresql://postgresql:postgresql@db/tests
      GHCI__SQLALCHEMY__POOL_RECYCLE: '3600'
      GHCI__SQLALCHEMY__POOL_SIZE: '10'
      GHCI__SQLALCHEMY__MAX_OVERFLOW: '20'
      GHCI__SESSION_SECRET: '1234'
      GHCI__CONFIGURATION: /etc/ghci/config.yaml
      GHCI__SERVICE_URL: http://localhost:8080/
      GHCI__APPLICATION__TEST__GITHUB_APP_ID: ${GHCI_TEST_GITHUB_APP_ID}
      GHCI__APPLICATION__TEST__GITHUB_APP_PRIVATE_KEY: ${GHCI_TEST_GITHUB_APP_PRIVATE_KEY}
      GHCI__APPLICATION__TEST__GITHUB_APP_URL: https://github.com/apps/test
      GHCI__APPLICATION__TEST__TITLE: Main application
      GHCI__APPLICATION__TEST__DESCRIPTION: This is the main application
      GHCI__APPLICATION__TEST__MODULES: test
      PGHOST: db
      PGUSER: postgresql
      PGPASSWORD: postgresql
      PGDATABASE: tests
      PGPORT: '5432'
    volumes:
      - ./docker/test-app/config.yaml:/etc/ghci/config.yaml:ro
      - ./github_app_geo_project:/app/github_app_geo_project:ro
    links:
      - db
    ports:
      - '9120:8080'

  worker:
    <<: *app
    command:
      - 'true'
    environment:
      <<: *app-env
      GHCI__PROCESS_QUEUE__MAX_WORKERS: 2
    ports: []
    volumes:
      - ./docker/test-app/config.yaml:/etc/ghci/config.yaml:ro
      - ./github_app_geo_project:/app/github_app_geo_project:ro
      - ./results:/results:rw

  tests:
    image: camptocamp/github-app-geo-project-tests
    build:
      context: .
      target: tests
    environment: *app-env
    command:
      - sleep
      - infinity
    links:
      - db
    volumes:
      - ./acceptance_tests:/acceptance_tests:rw
      - ./results:/results:rw
