#!/usr/bin/env python3
# Copyright (c) 2026 Camptocamp SA

import asyncio
import logging
import sys

import asyncpg

_LOGGER = logging.getLogger(__name__)


async def _wait_for_db(host: str, max_sleep: int = 60) -> bool:
    sleep_time = 1
    while sleep_time < max_sleep:
        print(f"Waiting for the DataBase server '{host}' to be reachable")
        try:
            connection = await asyncpg.connect(
                host=host,
                password="postgresql",  # noqa: S106
                user="postgresql",
                database="tests",
            )
        except Exception as exception:  # noqa: BLE001
            print(str(exception))
            await asyncio.sleep(sleep_time)
            sleep_time *= 2
        else:
            await connection.execute("SELECT 1")
            await connection.close()
            return True
    return False


async def _async_main() -> None:
    result = await _wait_for_db("db")
    sys.exit(0 if result else 1)


if __name__ == "__main__":
    asyncio.run(_async_main())
