#!/usr/bin/env python3
# pylint: disable=invalid-name

import sys
import time

import psycopg2


def _main() -> None:
    sleep_time = 1
    max_sleep = 60

    # Wait for the db to be UP
    for db in ("db",):
        while sleep_time < max_sleep:
            print(f"Waiting for the DataBase server '{db}' to be reachable")
            try:
                connection = psycopg2.connect(
                    host=db,
                    password="postgresql",  # noqa: S106
                    user="postgresql",
                    database="tests",
                )
                cursor = connection.cursor()
                cursor.execute("SELECT 1")
                break
            except Exception as e:  # noqa: BLE001
                print(str(e))
                time.sleep(sleep_time)
                sleep_time *= 2
    sys.exit(0 if sleep_time < max_sleep else 1)


if __name__ == "__main__":
    _main()
