# Used to test the workflow dashboard
name: Failed workflow

on:
  push:
    branches:
      - master

jobs:
  main1:
    name: Main 1
    runs-on: ubuntu-24.04
    timeout-minutes: 1

    steps:
      - run: 'false'

  main2:
    name: Main 2
    runs-on: ubuntu-24.04
    timeout-minutes: 1

    steps:
      - run: 'false'
