name: Continuous integration

on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
    tags:
      - '*'
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  main:
    name: Continuous integration
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"
    outputs:
      success: ${{ steps.success.outputs.success }}
    permissions:
      contents: read

    steps:
      - run: df -h
      - run: docker system prune --all --force
      # Inspired by https://github.com/jlumbroso/free-disk-space/
      - run: sudo rm -rf /usr/local/lib/android /usr/share/dotnet "$AGENT_TOOLSDIRECTORY"
      - run: df -h

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0

      - run: python3 -m pip install --requirement=ci/requirements.txt
      - name: Environment
        run: c2cciutils-env

      - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: "pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}\npre-commit-"
      - run: pre-commit run --all-files --color=always
      - run: git diff --exit-code --patch > /tmp/pre-commit.patch; git diff --color; git reset --hard || true
        if: failure()
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Apply pre-commit fix.patch
          path: /tmp/pre-commit.patch
          retention-days: 1
        if: failure()

      - run: pip install --requirement=requirements.txt
      - run: poetry install --all-extras --all-groups
      - run: poetry run prospector --output-format=pylint --ignore-paths=scripts

      - run: |
          echo GHCI_TEST_GITHUB_APP_ID=1234 > .env
          echo GHCI_TEST_GITHUB_APP_PRIVATE_KEY=5678 >> .env
      - run: make build
      - run: make tests
      - run: make acceptance-tests

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Acceptance tests
          path: results
        if: failure()
      - run: c2cciutils-docker-logs
        if: always()

      - name: Mark success
        id: success
        run: echo "success=true" >> "$GITHUB_OUTPUT"

  publish:
    name: Publish
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    needs:
      - main
    permissions:
      contents: write
      packages: write
      id-token: write
    environment:
      name: publish

    steps:
      - name: Ensure main job succeeded
        run: '[[ "${{ needs.main.outputs.success }}" == "true" ]]'
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - run: docker compose build

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      - run: python3 -m pip install --requirement=ci/requirements.txt
      - run: tag-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: env.HAS_SECRETS == 'HAS_SECRETS'
      - run: git diff --exit-code --patch > /tmp/dpkg-versions.patch; git diff --color; git reset --hard || true
        if: failure()
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Update dpkg versions list.patch
          path: /tmp/dpkg-versions.patch
          retention-days: 1
        if: failure()
      - uses: actions/upload-artifact@v7
        with:
          name: Update dpkg packages list.patch
          path: /tmp/dpkg.patch
          retention-days: 1
        if: failure()
